name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload HTML file to EC2
        run: |
          scp -i ~/.ssh/id_rsa netflix.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp

      - name: Move HTML to web root
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo mv /tmp/netflix.html /var/www/html/index.html && sudo systemctl restart nginx'
